on:
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          - runs-on: macos-latest
            arch: osx-x64
          - runs-on: ubuntu-latest
            arch: linux-x64
          
    steps:
    - uses: actions/checkout@v1

    - name: restore
      run: dotnet restore utauPlugin.Test -r ${{ matrix.os.arch }}

    - name: build
      run: dotnet build utauPlugin.Test
    
    - run: ls utauPlugin.Test/bin/Debug/net6.0 
    
    - run: ls utauPlugin.Test/bin/Debug/net6.0/inputData

    - name: unit test
      run: dotnet test utauPlugin.Test